open! Core
include Thing

type _u =
  { approved_at_utc : Time.t option option (* null *)
  ; subreddit : unit (* "opera" *)
  ; selftext : unit (* "" *)
  ; user_reports : unit (* [] *)
  ; saved : unit (* false *)
  ; mod_reason_title : unit (* null *)
  ; gilded : unit (* 0 *)
  ; clicked : unit (* false *)
  ; title : unit (* "Franco Zeffirelli, revered Italian director, dies aged 96" *)
  ; link_flair_richtext : unit (* [] *)
  ; subreddit_name_prefixed : unit (* "r/opera" *)
  ; hidden : unit (* false *)
  ; pwls : unit (* null *)
  ; link_flair_css_class : unit (* null *)
  ; downs : unit (* 0 *)
  ; parent_whitelist_status : unit (* null *)
  ; hide_score : unit (* false *)
  ; name : unit (* "t3_c0wmie" *)
  ; quarantine : unit (* false *)
  ; link_flair_text_color : unit (* "dark" *)
  ; upvote_ratio : unit (* 0.99 *)
  ; author_flair_background_color : unit (* null *)
  ; subreddit_type : unit (* "public" *)
  ; ups : unit (* 69 *)
  ; total_awards_received : unit (* 0 *)
  ; media_embed : unit (* null *)
  ; author_flair_template_id : unit (* null *)
  ; is_original_content : unit (* false *)
  ; author_fullname : unit (* "t2_7efau" *)
  ; secure_media : unit (* null *)
  ; is_reddit_media_domain : unit (* false *)
  ; is_meta : unit (* false *)
  ; category : unit (* null *)
  ; secure_media_embed : unit (* null *)
  ; link_flair_text : unit (* null *)
  ; can_mod_post : unit (* false *)
  ; score : unit (* 69 *)
  ; approved_by : unit (* null *)
  ; thumbnail : unit (* "" *)
  ; edited : unit (* false *)
  ; author_flair_css_class : unit (* null *)
  ; author_flair_richtext : unit (* [] *)
  ; gildings : unit (* null *)
  ; content_categories : unit (* null *)
  ; is_self : unit (* false *)
  ; mod_note : unit (* null *)
  ; created : unit (* 1560629330.0 *)
  ; link_flair_type : unit (* "text" *)
  ; wls : unit (* null *)
  ; banned_by : unit (* null *)
  ; author_flair_type : unit (* "text" *)
  ; domain : unit (* "theguardian.com" *)
  ; selftext_html : unit (* null *)
  ; likes : unit (* null *)
  ; suggested_sort : unit (* null *)
  ; banned_at_utc : Time.t option option (* null *)
  ; view_count : unit (* null *)
  ; archived : unit (* false *)
  ; no_follow : unit (* false *)
  ; is_crosspostable : unit (* true *)
  ; pinned : unit (* false *)
  ; over_18 : unit (* false *)
  ; all_awardings : unit (* [] *)
  ; media : unit (* null *)
  ; media_only : unit (* false *)
  ; can_gild : unit (* true *)
  ; spoiler : unit (* false *)
  ; locked : unit (* false *)
  ; author_flair_text : unit (* null *)
  ; visited : unit (* false *)
  ; num_reports : unit (* null *)
  ; distinguished : unit (* null *)
  ; subreddit_id : unit (* "t5_2r8vy" *)
  ; mod_reason_by : unit (* null *)
  ; removal_reason : unit (* null *)
  ; link_flair_background_color : unit (* "" *)
  ; id : unit (* "c0wmie" *)
  ; is_robot_indexable : unit (* true *)
  ; report_reasons : unit (* null *)
  ; author : unit (* "1810to1856" *)
  ; num_crossposts : unit (* 0 *)
  ; num_comments : unit (* 9 *)
  ; send_replies : unit (* true *)
  ; contest_mode : unit (* false *)
  ; author_patreon_flair : unit (* false *)
  ; author_flair_text_color : unit (* null *)
  ; permalink : unit
        (* "/r/opera/comments/c0wmie/franco_zeffirelli_revered_italian_director_dies/" *)
  ; whitelist_status : unit (* null *)
  ; stickied : unit (* false *)
  ; url : unit
        (* "https://www.theguardian.com/stage/2019/jun/15/franco-zeffirelli-revered-italian-director-dies-aged-96" *)
  ; subreddit_subscribers : unit (* 11109 *)
  ; created_utc : Time.t option option (* 1560600530.0 *)
  ; mod_reports : unit (* [] *)
  ; is_video : unit (* false *)
  }
